In [1]:
print('Hello world')

Hello world


In [2]:
import numpy as np

In [4]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
a1.dtype

dtype('int32')

In [7]:
data2 = ([0.1, 5., 4., 12., 0.4])
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.4])

In [8]:
a2.dtype

dtype('float64')

In [10]:
a3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a3.dtype

dtype('int32')

In [12]:
a3.shape

(3, 3)

In [13]:
a1.shape

(6,)

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [26]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [27]:
np.linspace(0,np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
d1=np.ones((4,8))

In [36]:
d1.dtype

dtype('float64')

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
str_a1 = np.array(['1.5','2','3.14','4.54','8'])
num_a1=str_a1.astype(float)
num_a1

array([1.5 , 2.  , 3.14, 4.54, 8.  ])

In [40]:
str_a1.dtype

dtype('<U4')

In [41]:
num_a1.dtype

dtype('float64')

In [46]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[4,3,2],[7,6,5],[1,9,8]])
arr1/arr2

array([[0.25      , 0.66666667, 1.5       ],
       [0.57142857, 0.83333333, 1.2       ],
       [7.        , 0.88888889, 1.125     ]])

In [47]:
arr1 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [51]:
arr2_bool = arr2 < 5

In [52]:
arr2_bool.dtype

dtype('bool')

In [53]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [54]:
a[a%2 == 0]

array([2, 4, 6])

In [55]:
str_a1

array(['1.5', '2', '3.14', '4.54', '8'], dtype='<U4')

In [56]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [57]:
b1[:3]

array([ 0, 10, 20])

In [58]:
b1[2:5]=np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

ValueError: could not broadcast input array from shape (3) into shape (4)